### ISSUE TITLE
不要な情報を隠す

### ISSUE THREAD

**Issue by dellin** [chiracity/project#13]
> Title: 『親子でリズムあそび』～リズム教室　♪ぽこあぽこ♪
> FileName: 161227_pokoapoko2017.1
> EventStartAt: 2017-01-27 10:00
> EventEndAt: 2017-02-22 13:40
> ShowStartAt:
> ShowEndAt:
> Organizer: リズム教室 ♪ぽこあぽこ♪
> Location: 小金原市民センター 2F和室

の場合、αで個別ページで見えるのは、以下のテキストに差し替える

> 『親子でリズムあそび』～リズム教室　♪ぽこあぽこ♪
> ※下のサムネイル画像をクリック/タップすると、PDFが開きます。

Debug用に、HTMLコメントの形で残しておくのはOK。

**Comment by koba-ninkigumi** [comment]
対応完了
